name: 汉化

on:
  workflow_dispatch:
    inputs:
      download_link:
        description: '文件下载链接'
        required: true
      release_tag:
        description: '发行版标签'
        required: true
      release_title:
        description: '发行版标题'
        required: true

jobs:
  hanhua:
    runs-on: ubuntu-latest

    steps:
    - name: 初始化仓库
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: 下载文件并重命名为 copilot.zip
      run: |
        curl -L ${{ github.event.inputs.download_link }} -o copilot.zip

    - name: 解压 copilot.zip 到当前文件夹
      run: |
        unzip copilot.zip

    - name: 解压 core.jar 到当前文件夹
      run: |
        unzip github-copilot-intellij/lib/core.jar -d core_jar_contents

    - name: 汉化
      run: |
        python3 2.replace.py

    - name: 移动 copilot.properties 文件
      run: |
        mv copilot.properties github-copilot-intellij/lib/core/copilot/

    - name: 将 core 目录重新打包到 core.jar
      run: |
        cd core_jar_contents
        zip -r ../core.jar *
        cd ..
        mv core.jar github-copilot-intellij/lib/
        rm -rf core_jar_contents

    - name: 打包为发行版文件
      run: |
        zip -r github-copilot-intellij-${{ github.event.inputs.release_tag }}.zip github-copilot-intellij

    - name: 创建 GitHub 发行版并上传文件
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      with:
        tag_name: ${{ inputs.release_tag }}
        release_name: ${{ inputs.release_title }}
        body: |
          这是一个自动发布的发行版。
        draft: false
        prerelease: false
        files: github-copilot-intellij-${{ inputs.release_tag }}.zip
